import {StyleSheet} from 'react-native';

import type {Colors} from './colors';
export {darkColors, lightColors} from './colors';
export function createStyles(c: Colors) { return StyleSheet.create({
  root: {flex: 1, backgroundColor: c.bg},
  workspace: {flex: 1, flexDirection: 'row', paddingHorizontal: 20, paddingBottom: 18, gap: 16},
  libraryDock: {width: 250, backgroundColor: c.sidebar, borderRadius: 14, overflow: 'hidden'},
  discussionDock: {width: 340, backgroundColor: c.panel, borderWidth: 1, borderColor: c.separator, borderRadius: 14, overflow: 'hidden'},
  workspaceHeader: {height: 70, paddingHorizontal: 22, gap: 12, flexDirection: 'row', alignItems: 'center', backgroundColor: c.bg},
  breadcrumb: {flexDirection: 'row', alignItems: 'center', gap: 4, flex: 1, minWidth: 0},
  breadcrumbPart: {maxWidth: 180},
  breadcrumbSlash: {fontSize: 17, color: c.faint, marginHorizontal: 5},
  headerDivider: {width: 1, height: 22, backgroundColor: c.separator, marginHorizontal: 3},
  brandButton: {flexDirection: 'row', alignItems: 'center', gap: 9, borderRadius: 9, paddingVertical: 8, paddingRight: 12},
  brandMark: {height: 26, width: 26, borderRadius: 8, backgroundColor: c.accent, alignItems: 'center', justifyContent: 'center'},
  avatarButton: {padding: 3, borderRadius: 22, borderWidth: 2, borderColor: 'transparent'},
  playerFrame: {flex: 1, borderRadius: 14, overflow: 'hidden', backgroundColor: '#101012'},
  drawingPalette: {position: 'absolute', top: 20, left: 78, flexDirection: 'row', padding: 7, gap: 5, borderRadius: 12, backgroundColor: c.panel, borderWidth: 1, borderColor: c.separator},
  libraryPopover: {position: 'absolute', zIndex: 4, top: 74, left: 16, width: 330, bottom: 20, backgroundColor: c.panel, borderWidth: 1, borderColor: c.line, borderRadius: 16, overflow: 'hidden'},
  popoverHeader: {paddingHorizontal: 12, height: 60, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between'},
  popoverDismiss: {position: 'absolute', zIndex: 3, top: 68, left: 0, right: 0, bottom: 0},
  brand: {color: c.text, fontSize: 18, fontWeight: '700', letterSpacing: -0.6},
  sidebarScroll: {flex: 1},
  sideSection: {paddingHorizontal: 12, marginBottom: 20},
  sectionRow: {minHeight: 36, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingLeft: 8, marginBottom: 7},
  sectionTitle: {color: c.muted, fontSize: 12, fontWeight: '600'},
  navItem: {flex: 1, minWidth: 0, minHeight: 38, paddingHorizontal: 9, paddingVertical: 6, borderRadius: 6, flexDirection: 'row', justifyContent: 'flex-start', alignItems: 'center', gap: 9, backgroundColor: 'transparent'},
  navSelected: {backgroundColor: c.selected, borderColor: c.selectedLine},
  navIcon: {fontSize: 15, lineHeight: 20, color: c.muted, width: 19, textAlign: 'center'},
  navText: {fontSize: 13, lineHeight: 19, color: c.text, flex: 1},
  sidebarBottom: {padding: 14, borderTopWidth: 1, borderTopColor: c.separator, gap: 12},
  profileButton: {paddingHorizontal: 6, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 9, height: 40},
  profileName: {color: c.text, fontSize: 14, fontWeight: '600', lineHeight: 20, flex: 1},
  chevron: {color: c.muted, fontSize: 21, lineHeight: 26, width: 14, textAlign: 'center'},
  stage: {flex: 1, minWidth: 300},
  videoHeader: {position: 'absolute', top: 12, left: 16, right: 16, height: 44, paddingHorizontal: 8, flexDirection: 'row', alignItems: 'center', gap: 12, borderRadius: 12, backgroundColor: '#15191deb'},
  titleBlock: {flex: 1, minWidth: 80},
  title: {color: c.text, fontSize: 13, fontWeight: '500', letterSpacing: -0.1},
  playerArea: {flex: 1, backgroundColor: '#101012', overflow: 'hidden', minHeight: 240},
  nativePlayer: {flex: 1},
  transport: {paddingHorizontal: 10, paddingTop: 2, paddingBottom: 6},
  transportRow: {flexDirection: 'row', alignItems: 'center', gap: 4, paddingTop: 4},
  playButton: {width: 40, height: 36},
  time: {color: c.text, fontSize: 12, fontVariant: ['tabular-nums'], marginHorizontal: 5},
  transportSpacer: {flex: 1},
  statusRow: {minHeight: 29, flexDirection: 'row', justifyContent: 'flex-end', alignItems: 'center', paddingHorizontal: 20, paddingBottom: 12},
  status: {color: c.muted, fontSize: 11, flex: 1},
  toolBar: {position: 'absolute', left: 16, top: 20, padding: 6, borderWidth: 1, borderColor: c.separator, backgroundColor: c.panel, borderRadius: 16, alignItems: 'center', gap: 5},
  toolDivider: {height: 20, width: 1, backgroundColor: c.line, marginHorizontal: 5},
  swatch: {height: 30, width: 30, borderRadius: 13, borderWidth: 2, borderColor: 'transparent', padding: 3},
  swatchSelected: {borderColor: c.text},
  swatchFill: {flex: 1, borderRadius: 10, borderWidth: 1, borderColor: '#526578'},
  discussionPopover: {position: 'absolute', zIndex: 4, top: 74, right: 16, bottom: 126, backgroundColor: c.panel, borderWidth: 1, borderColor: c.line, borderRadius: 16, overflow: 'hidden'},
  railHeader: {height: 60, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', gap: 6},
  railTitle: {color: c.text, fontSize: 15, fontWeight: '600'},
  railContent: {paddingHorizontal: 14, paddingBottom: 16},
  commentCard: {borderBottomWidth: 1, borderLeftWidth: 3, borderColor: c.separator, borderLeftColor: 'transparent', borderRadius: 12, padding: 14, marginBottom: 8, backgroundColor: c.panel},
  commentSelected: {borderLeftColor: c.selectedLine, backgroundColor: c.selected},
  commentHeader: {flexDirection: 'row', alignItems: 'center', gap: 7, marginBottom: 9},
  commentAuthor: {color: c.text, fontSize: 15, lineHeight: 21, fontWeight: '700', flex: 1},
  commentDate: {color: c.faint, fontSize: 10, lineHeight: 16},
  commentText: {color: c.text, fontSize: 14, lineHeight: 21},
  commentAnchor: {color: c.accentText, fontSize: 11, fontWeight: '600', fontVariant: ['tabular-nums']},
  commentMeta: {flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: 11},
  commentActions: {flexDirection: 'row', alignItems: 'center', gap: 5, marginTop: 10, flexWrap: 'wrap'},
  threadRow: {borderLeftWidth: 1, borderLeftColor: c.separator, marginLeft: 18, paddingLeft: 7},
  replyCard: {backgroundColor: c.inset, borderBottomWidth: 0, borderRadius: 8, padding: 11, marginBottom: 10},
  replyHeader: {marginBottom: 6},
  replyAuthor: {fontSize: 12, lineHeight: 18, fontWeight: '600', color: c.muted},
  replyText: {fontSize: 13, lineHeight: 19},
  replyMeta: {marginTop: 8},
  replyActions: {marginTop: 6},
  replyToggle: {width: 116, height: 32, justifyContent: 'center', paddingHorizontal: 5, borderRadius: 8},
  replyToggleText: {color: c.text, fontSize: 12, fontWeight: '600'},
  emptyComments: {padding: 22, paddingTop: 40, alignItems: 'center'},
  emptyCommentsText: {color: c.muted, fontSize: 12, lineHeight: 18},
  draft: {padding: 16, borderTopWidth: 1, borderTopColor: c.separator, backgroundColor: c.panel},
  draftHeader: {flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between'},
  composerDock: {padding: 12, borderBottomWidth: 1, borderBottomColor: c.separator},
  composerCollapsed: {paddingVertical: 6},
  composerAction: {height: 36, minWidth: 76},
  draftTitle: {color: c.text, fontSize: 14, fontWeight: '600'},
  input: {borderWidth: 1, borderColor: c.line, borderRadius: 7, backgroundColor: c.input, color: c.text, paddingHorizontal: 11, paddingVertical: 9, fontSize: 13},
  textArea: {minHeight: 76, maxHeight: 150, textAlignVertical: 'top', lineHeight: 19},
  segment: {flexDirection: 'row', backgroundColor: c.inset, borderRadius: 7, padding: 3, gap: 3, marginTop: 12},
  segmentButton: {flex: 1, minHeight: 29},
  anchorRow: {flexDirection: 'row', alignItems: 'flex-end', gap: 7, marginTop: 9},
  anchorInput: {flex: 1, fontSize: 12, fontVariant: ['tabular-nums'], paddingHorizontal: 8},
  fieldLabel: {color: c.muted, fontSize: 11, marginBottom: 5},
  anchorField: {flex: 1},
  hint: {color: c.muted, fontSize: 11, lineHeight: 16, marginTop: 10},
  draftActions: {flexDirection: 'row', alignItems: 'center', gap: 7, marginTop: 13, flexWrap: 'wrap'},
  errorBar: {flexDirection: 'row', alignItems: 'center', backgroundColor: c.errorBg, paddingHorizontal: 18, paddingVertical: 11, gap: 12, borderBottomWidth: 1, borderBottomColor: c.danger},
  errorText: {color: c.errorText, fontSize: 12, lineHeight: 18, flex: 1},
  button: {flexDirection: 'row', gap: 7, borderWidth: 1, borderColor: c.separator, paddingHorizontal: 12, minHeight: 36, paddingVertical: 6, borderRadius: 9, justifyContent: 'center', alignItems: 'center', backgroundColor: c.button},
  buttonCompact: {minHeight: 32, minWidth: 32, paddingHorizontal: 7, paddingVertical: 4},
  buttonPrimary: {backgroundColor: c.accent, borderColor: c.accentText},
  buttonActive: {backgroundColor: c.selected, borderColor: c.selectedLine},
  buttonPressed: {opacity: 0.7},
  buttonDisabled: {backgroundColor: c.disabled, borderColor: c.separator, opacity: 0.65},
  buttonText: {flexShrink: 1, fontSize: 12, lineHeight: 17, fontWeight: '500', color: c.text},
  buttonPrimaryText: {color: c.primaryText, fontWeight: '600'},
  disabledText: {color: c.faint},
  accentText: {color: c.accentText},
  mutedText: {color: c.muted},
  empty: {flex: 1, justifyContent: 'center', alignItems: 'center', padding: 35, gap: 14},
  emptyTitle: {color: c.text, fontSize: 19, fontWeight: '600', letterSpacing: -0.4, textAlign: 'center'},
  emptyBody: {color: c.muted, fontSize: 13, lineHeight: 20, textAlign: 'center', maxWidth: 310},
  modalBackdrop: {...StyleSheet.absoluteFillObject, zIndex: 1000, backgroundColor: '#00000066', justifyContent: 'center', alignItems: 'center', padding: 30},
  modal: {width: 390, maxWidth: '100%', backgroundColor: c.panel, borderWidth: 1, borderColor: c.line, borderRadius: 13, padding: 24},
  modalTitle: {color: c.text, fontSize: 20, fontWeight: '600', letterSpacing: -0.4, marginBottom: 18},
  modalBody: {color: c.muted, fontSize: 13, lineHeight: 20, marginBottom: 19},
  modalActions: {flexDirection: 'row', justifyContent: 'flex-end', gap: 8, marginTop: 20},
  themeOptions: {flexDirection: 'row', gap: 5, marginTop: 8},
  themeLabel: {color: c.muted, fontSize: 12, marginTop: 22},
  navRow: {flexDirection: 'row', alignItems: 'center', gap: 3, marginBottom: 4},
  focusRing: {borderColor: c.text, backgroundColor: c.selected},
  buttonHover: {backgroundColor: c.selected, borderColor: c.separator},
  buttonDanger: {backgroundColor: c.errorBg, borderColor: c.danger},
  commentActive: {borderLeftColor: c.selectedLine},
  settingsPage: {flex: 1, width: '100%', maxWidth: 1060, alignSelf: 'center', backgroundColor: c.bg, paddingHorizontal: 48, paddingTop: 28},
  settingsHeader: {flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 24},
  settingsTitle: {fontSize: 26, fontWeight: '600', color: c.text, letterSpacing: -0.6},
  settingsTabs: {flexDirection: 'row', gap: 8, marginBottom: 24},
  settingsContent: {paddingBottom: 40, maxWidth: 860, width: '100%', alignSelf: 'center'},
  settingsSectionTitle: {color: c.text, fontSize: 15, fontWeight: '600', marginTop: 18, marginBottom: 12},
  appearanceChoice: {flex: 1, height: 64},
  preferenceRow: {flexDirection: 'row', alignItems: 'center', gap: 16, marginTop: 32, paddingVertical: 16, borderTopWidth: 1, borderTopColor: c.separator},
  preferenceLabel: {flex: 1, color: c.text, fontSize: 14, lineHeight: 20},
  shortcutSearch: {flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 10},
  shortcutRow: {flexDirection: 'row', alignItems: 'center', gap: 10, minHeight: 52, borderBottomWidth: 1, borderBottomColor: c.separator},
  keycap: {minWidth: 130},
  buttonQuiet: {backgroundColor: 'transparent', borderColor: 'transparent'},
  playerPresent: {marginHorizontal: 0, marginBottom: 0, borderRadius: 0},
  videoControls: {position: 'absolute', bottom: 0, left: 0, right: 0, backgroundColor: '#19191bea', borderTopWidth: 1, borderColor: '#ffffff18', paddingHorizontal: 12, paddingTop: 2, paddingBottom: 7},
  videoNotes: {position: 'absolute', top: 20, right: 20, bottom: 112, width: 310, maxWidth: '70%', flexGrow: 0},
  videoNotesLarge: {top: 76, width: 400},
  videoNotesContent: {gap: 10},
  videoNote: {padding: 14, backgroundColor: '#20252bf5', borderRadius: 14, borderWidth: 1, borderColor: '#697789', borderLeftWidth: 3},
  videoNoteLarge: {padding: 18},
  videoNoteText: {fontSize: 24, lineHeight: 34},
  composer: {position: 'absolute', top: 76, right: 16, width: 340, maxWidth: '85%', padding: 12, backgroundColor: '#20252bfa', borderWidth: 1, borderColor: '#697789', borderRadius: 14},
  loading: {flex: 1, alignItems: 'center', justifyContent: 'center', gap: 16},
}); }
