import {StyleSheet} from 'react-native';

export const darkColors = {
  bg: '#191d23', panel: '#232932', sidebar: '#20262e', inset: '#191f27',
  line: '#3d4856', text: '#eef3f9', muted: '#aebaca', faint: '#9caabd',
  accent: '#9fcfff', accentText: '#b2d9ff', primaryText: '#12334f', selected: '#293f55',
  selectedLine: '#78b5ed', button: '#364352', disabled: '#29323e', input: '#1c242e',
  avatar: '#354b62', danger: '#ffb5b1', errorBg: '#4c2e35', errorText: '#ffe5e2',
};
export const lightColors: typeof darkColors = {
  bg: '#f6f8fb', panel: '#ffffff', sidebar: '#edf1f6', inset: '#f1f5f9',
  line: '#cbd4df', text: '#1d2a38', muted: '#526274', faint: '#596c80',
  accent: '#9fcfff', accentText: '#175786', primaryText: '#12334f', selected: '#e0efff',
  selectedLine: '#6aa6d7', button: '#e3eaf2', disabled: '#edf1f6', input: '#f8fafc',
  avatar: '#d5e8fb', danger: '#a42b36', errorBg: '#ffebe8', errorText: '#81252d',
};
export type Colors = typeof darkColors;
export function createStyles(c: Colors) { return StyleSheet.create({
  root: {flex: 1, backgroundColor: c.bg},
  workspace: {flex: 1, flexDirection: 'row'},
  sidebar: {width: 218, backgroundColor: c.sidebar, borderRightWidth: 1, borderRightColor: c.line},
  sidebarTop: {paddingHorizontal: 20, paddingTop: 24, paddingBottom: 20},
  brand: {color: c.text, fontSize: 20, fontWeight: '700', letterSpacing: -0.7},
  sidebarScroll: {flex: 1},
  sideSection: {paddingHorizontal: 12, marginBottom: 20},
  sectionRow: {flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingLeft: 8, marginBottom: 7},
  sectionTitle: {color: c.muted, fontSize: 12, fontWeight: '600'},
  navItem: {minHeight: 36, paddingHorizontal: 10, paddingVertical: 9, borderRadius: 7, marginBottom: 3, flexDirection: 'row', alignItems: 'center', gap: 9},
  navSelected: {backgroundColor: c.selected},
  navIcon: {fontSize: 15, lineHeight: 20, color: c.muted, width: 19, textAlign: 'center'},
  navText: {fontSize: 13, lineHeight: 19, color: c.text, flex: 1},
  sidebarBottom: {padding: 16, borderTopWidth: 1, borderTopColor: c.line, gap: 12},
  profileButton: {flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 9, height: 40},
  avatar: {height: 28, width: 28, borderRadius: 14, backgroundColor: c.avatar, justifyContent: 'center', alignItems: 'center'},
  avatarText: {color: c.accentText, fontSize: 12, lineHeight: 16, fontWeight: '600', textAlign: 'center'},
  profileName: {color: c.text, fontSize: 12, lineHeight: 18, flex: 1},
  chevron: {color: c.muted, fontSize: 21, lineHeight: 26, width: 14, textAlign: 'center'},
  stage: {flex: 1, minWidth: 350},
  toolbar: {height: 74, paddingHorizontal: 24, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 16},
  titleBlock: {flex: 1, minWidth: 80},
  title: {color: c.text, fontSize: 17, fontWeight: '600', letterSpacing: -0.3},
  playerArea: {flex: 1, backgroundColor: '#000000', marginHorizontal: 22, borderRadius: 10, overflow: 'hidden', minHeight: 180},
  nativePlayer: {flex: 1},
  transport: {paddingHorizontal: 22, paddingTop: 13, paddingBottom: 18},
  transportRow: {flexDirection: 'row', alignItems: 'center', gap: 8, paddingTop: 8},
  playButton: {width: 38},
  time: {color: c.text, fontSize: 12, fontVariant: ['tabular-nums'], marginHorizontal: 5},
  transportSpacer: {flex: 1},
  statusRow: {minHeight: 29, flexDirection: 'row', justifyContent: 'flex-end', alignItems: 'center', paddingHorizontal: 22, paddingBottom: 12},
  status: {color: c.muted, fontSize: 11, flex: 1},
  toolBar: {paddingHorizontal: 22, paddingBottom: 16, flexDirection: 'row', alignItems: 'center', gap: 6, flexWrap: 'wrap'},
  toolDivider: {height: 20, width: 1, backgroundColor: c.line, marginHorizontal: 5},
  swatch: {height: 25, width: 25, borderRadius: 13, borderWidth: 2, borderColor: 'transparent', padding: 3},
  swatchSelected: {borderColor: c.text},
  swatchFill: {flex: 1, borderRadius: 10, borderWidth: 1, borderColor: '#526578'},
  rail: {width: 326, backgroundColor: c.panel, borderLeftWidth: 1, borderLeftColor: c.line},
  railHeader: {height: 74, paddingHorizontal: 20, flexDirection: 'row', alignItems: 'center'},
  railTitle: {color: c.text, fontSize: 15, fontWeight: '600'},
  railContent: {paddingHorizontal: 14, paddingBottom: 16},
  commentCard: {borderWidth: 1, borderColor: c.line, borderRadius: 9, padding: 13, marginBottom: 9, backgroundColor: c.panel},
  commentSelected: {borderColor: c.selectedLine, backgroundColor: c.selected},
  commentHeader: {flexDirection: 'row', alignItems: 'center', gap: 7, marginBottom: 9},
  commentAuthor: {color: c.text, fontSize: 12, lineHeight: 18, fontWeight: '600', flex: 1},
  commentDate: {color: c.faint, fontSize: 10, lineHeight: 16},
  commentText: {color: c.text, fontSize: 13, lineHeight: 19},
  commentAnchor: {color: c.accentText, fontSize: 11, fontWeight: '600', fontVariant: ['tabular-nums']},
  commentMeta: {flexDirection: 'row', alignItems: 'center', marginTop: 11},
  commentActions: {flexDirection: 'row', alignItems: 'center', gap: 5, marginTop: 10, flexWrap: 'wrap'},
  threadRow: {borderLeftWidth: 1, borderLeftColor: c.line, paddingLeft: 9},
  replyToggle: {alignSelf: 'flex-start', paddingVertical: 5, paddingHorizontal: 2, marginTop: 3},
  replyToggleText: {color: c.accentText, fontSize: 11, fontWeight: '500'},
  emptyComments: {padding: 22, paddingTop: 40, alignItems: 'center'},
  emptyCommentsText: {color: c.muted, fontSize: 12, lineHeight: 18},
  draft: {padding: 16, borderTopWidth: 1, borderTopColor: c.line, backgroundColor: c.panel},
  draftHeader: {flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 12},
  draftTitle: {color: c.text, fontSize: 14, fontWeight: '600'},
  input: {borderWidth: 1, borderColor: c.line, borderRadius: 7, backgroundColor: c.input, color: c.text, paddingHorizontal: 11, paddingVertical: 9, fontSize: 13},
  textArea: {minHeight: 92, maxHeight: 150, textAlignVertical: 'top', lineHeight: 19},
  segment: {flexDirection: 'row', backgroundColor: c.inset, borderRadius: 7, padding: 3, gap: 3, marginTop: 12},
  segmentButton: {flex: 1, minHeight: 29},
  anchorRow: {flexDirection: 'row', alignItems: 'center', gap: 7, marginTop: 9},
  anchorInput: {flex: 1, fontSize: 12, fontVariant: ['tabular-nums'], paddingHorizontal: 8},
  fieldLabel: {color: c.muted, fontSize: 11, marginBottom: 5},
  anchorField: {flex: 1},
  hint: {color: c.muted, fontSize: 11, lineHeight: 16, marginTop: 10},
  draftActions: {flexDirection: 'row', alignItems: 'center', gap: 7, marginTop: 13, flexWrap: 'wrap'},
  draftResume: {backgroundColor: c.inset, padding: 12, borderRadius: 8, marginBottom: 9},
  errorBar: {flexDirection: 'row', alignItems: 'center', backgroundColor: c.errorBg, paddingHorizontal: 18, paddingVertical: 11, gap: 12, borderBottomWidth: 1, borderBottomColor: c.danger},
  errorText: {color: c.errorText, fontSize: 12, lineHeight: 18, flex: 1},
  button: {paddingHorizontal: 12, minHeight: 33, paddingVertical: 7, borderRadius: 6, justifyContent: 'center', alignItems: 'center', backgroundColor: c.button},
  buttonCompact: {minHeight: 27, paddingHorizontal: 9, paddingVertical: 5},
  buttonPrimary: {backgroundColor: c.accent},
  buttonActive: {backgroundColor: c.selected},
  buttonPressed: {opacity: 0.7},
  buttonDisabled: {backgroundColor: c.disabled},
  buttonText: {fontSize: 12, lineHeight: 17, fontWeight: '500', color: c.text},
  buttonPrimaryText: {color: c.primaryText, fontWeight: '600'},
  disabledText: {color: c.faint},
  accentText: {color: c.accentText},
  mutedText: {color: c.muted},
  empty: {flex: 1, justifyContent: 'center', alignItems: 'center', padding: 35, gap: 14},
  emptyTitle: {color: c.text, fontSize: 19, fontWeight: '600', letterSpacing: -0.4, textAlign: 'center'},
  emptyBody: {color: c.muted, fontSize: 13, lineHeight: 20, textAlign: 'center', maxWidth: 310},
  modalBackdrop: {...StyleSheet.absoluteFillObject, zIndex: 1000, backgroundColor: '#00000066', justifyContent: 'center', alignItems: 'center', padding: 30},
  modal: {width: 390, maxWidth: '100%', backgroundColor: c.panel, borderWidth: 1, borderColor: c.line, borderRadius: 13, padding: 24},
  modalTitle: {color: c.text, fontSize: 20, fontWeight: '600', letterSpacing: -0.4, marginBottom: 18},
  modalBody: {color: c.muted, fontSize: 13, lineHeight: 20, marginBottom: 19},
  modalActions: {flexDirection: 'row', justifyContent: 'flex-end', gap: 8, marginTop: 20},
  themeOptions: {flexDirection: 'row', gap: 5, marginTop: 8},
  themeLabel: {color: c.muted, fontSize: 12, marginTop: 22},
  loading: {flex: 1, alignItems: 'center', justifyContent: 'center', gap: 16},
}); }
