import {StyleSheet} from 'react-native';

export const colors = {bg: '#181a1e', panel: '#22252a', sidebar: '#202328', inset: '#191b20',
  line: '#363940', text: '#f0f1f3', muted: '#a0a5af', faint: '#727984', accent: '#f09a77', danger: '#ffaca1'};
export const styles = StyleSheet.create({
  root: {flex: 1, backgroundColor: colors.bg},
  workspace: {flex: 1, flexDirection: 'row'},
  sidebar: {width: 218, backgroundColor: colors.sidebar, borderRightWidth: 1, borderRightColor: colors.line},
  sidebarTop: {paddingHorizontal: 20, paddingTop: 24, paddingBottom: 20},
  brand: {color: colors.text, fontSize: 20, fontWeight: '700', letterSpacing: -0.7},
  sidebarScroll: {flex: 1},
  sideSection: {paddingHorizontal: 12, marginBottom: 20},
  sectionRow: {flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingLeft: 8, marginBottom: 7},
  sectionTitle: {color: colors.muted, fontSize: 12, fontWeight: '600'},
  navItem: {minHeight: 36, paddingHorizontal: 10, paddingVertical: 9, borderRadius: 7, marginBottom: 3, flexDirection: 'row', alignItems: 'center', gap: 9},
  navSelected: {backgroundColor: '#36383e'},
  navIcon: {fontSize: 15, color: colors.muted, width: 19, textAlign: 'center'},
  navText: {fontSize: 13, color: colors.text, flex: 1},
  navCount: {fontSize: 11, color: colors.muted},
  sidebarBottom: {padding: 16, borderTopWidth: 1, borderTopColor: colors.line, gap: 10},
  profileButton: {flexDirection: 'row', alignItems: 'center', gap: 9, minHeight: 36},
  avatar: {height: 28, width: 28, borderRadius: 14, backgroundColor: '#454047', justifyContent: 'center', alignItems: 'center'},
  avatarText: {color: '#f2c8b5', fontSize: 12, fontWeight: '600'},
  profileName: {color: colors.text, fontSize: 12, flex: 1},
  storageText: {color: colors.faint, fontSize: 11, lineHeight: 16},
  stage: {flex: 1, minWidth: 350},
  toolbar: {height: 74, paddingHorizontal: 24, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 16},
  titleBlock: {flex: 1, minWidth: 80},
  title: {color: colors.text, fontSize: 17, fontWeight: '600', letterSpacing: -0.3},
  caption: {color: colors.muted, fontSize: 11, marginTop: 5},
  playerArea: {flex: 1, backgroundColor: '#0d0e11', marginHorizontal: 22, borderRadius: 10, overflow: 'hidden', minHeight: 180},
  nativePlayer: {flex: 1},
  transport: {paddingHorizontal: 22, paddingTop: 13, paddingBottom: 18},
  transportRow: {flexDirection: 'row', alignItems: 'center', gap: 8, paddingTop: 8},
  playButton: {width: 38},
  time: {color: '#d8dbe1', fontSize: 12, fontVariant: ['tabular-nums'], marginHorizontal: 5},
  transportSpacer: {flex: 1},
  statusRow: {minHeight: 31, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 30, paddingBottom: 10},
  status: {color: colors.muted, fontSize: 11, flex: 1},
  toolBar: {paddingHorizontal: 22, paddingTop: 2, paddingBottom: 16, flexDirection: 'row', alignItems: 'center', gap: 6, flexWrap: 'wrap'},
  toolDivider: {height: 20, width: 1, backgroundColor: colors.line, marginHorizontal: 5},
  swatch: {height: 23, width: 23, borderRadius: 12, borderWidth: 3, borderColor: 'transparent', padding: 2},
  swatchSelected: {borderColor: '#eee'},
  swatchFill: {flex: 1, borderRadius: 10},
  rail: {width: 326, backgroundColor: colors.panel, borderLeftWidth: 1, borderLeftColor: colors.line},
  railHeader: {height: 74, paddingHorizontal: 20, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center'},
  railTitle: {color: colors.text, fontSize: 15, fontWeight: '600'},
  countBadge: {color: colors.muted, fontSize: 12, marginLeft: 7},
  railContent: {paddingHorizontal: 14, paddingBottom: 16},
  commentCard: {borderWidth: 1, borderColor: colors.line, borderRadius: 9, padding: 13, marginBottom: 9, backgroundColor: '#26292f'},
  commentSelected: {borderColor: '#b77a61', backgroundColor: '#302c2b'},
  commentHeader: {flexDirection: 'row', alignItems: 'center', gap: 7, marginBottom: 9},
  commentAuthor: {color: colors.text, fontSize: 12, fontWeight: '600', flex: 1},
  commentDate: {color: colors.faint, fontSize: 10},
  commentText: {color: '#d8dbe0', fontSize: 13, lineHeight: 19},
  commentAnchor: {color: colors.accent, fontSize: 11, fontWeight: '600', fontVariant: ['tabular-nums']},
  commentMeta: {flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 11, gap: 6},
  commentActions: {flexDirection: 'row', gap: 5, marginTop: 10},
  replyContext: {color: colors.muted, fontSize: 10, marginBottom: 8},
  emptyComments: {padding: 22, paddingTop: 44, alignItems: 'center', gap: 9},
  emptyCommentsTitle: {color: '#ccd0d7', fontSize: 13, fontWeight: '600'},
  emptyCommentsText: {color: colors.muted, fontSize: 12, lineHeight: 18, textAlign: 'center'},
  draft: {padding: 16, borderTopWidth: 1, borderTopColor: colors.line, backgroundColor: '#282b31'},
  draftHeader: {flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 12},
  draftTitle: {color: colors.text, fontSize: 14, fontWeight: '600'},
  draftSave: {color: colors.muted, fontSize: 10},
  input: {borderWidth: 1, borderColor: '#454952', borderRadius: 7, backgroundColor: '#202228', color: colors.text, paddingHorizontal: 11, paddingVertical: 9, fontSize: 13},
  textArea: {minHeight: 92, maxHeight: 150, textAlignVertical: 'top', lineHeight: 19},
  segment: {flexDirection: 'row', backgroundColor: '#1d1f24', borderRadius: 7, padding: 3, gap: 3, marginTop: 12},
  segmentButton: {flex: 1, minHeight: 29},
  anchorRow: {flexDirection: 'row', alignItems: 'center', gap: 7, marginTop: 9},
  anchorInput: {flex: 1, fontSize: 12, fontVariant: ['tabular-nums'], paddingHorizontal: 8},
  fieldLabel: {color: colors.muted, fontSize: 11, marginBottom: 5},
  anchorField: {flex: 1},
  hint: {color: colors.muted, fontSize: 11, lineHeight: 16, marginTop: 10},
  draftActions: {flexDirection: 'row', alignItems: 'center', gap: 7, marginTop: 13},
  draftFooter: {color: colors.muted, fontSize: 10, marginTop: 10},
  draftResume: {backgroundColor: '#333239', padding: 12, borderRadius: 8, marginBottom: 9},
  errorBar: {flexDirection: 'row', alignItems: 'center', backgroundColor: '#4b2d2d', paddingHorizontal: 18, paddingVertical: 11, gap: 12, borderBottomWidth: 1, borderBottomColor: '#70413c'},
  errorText: {color: '#ffe0d9', fontSize: 12, lineHeight: 18, flex: 1},
  button: {paddingHorizontal: 12, minHeight: 33, paddingVertical: 7, borderRadius: 6, justifyContent: 'center', alignItems: 'center', backgroundColor: '#363a42'},
  buttonCompact: {minHeight: 27, paddingHorizontal: 9, paddingVertical: 5},
  buttonPrimary: {backgroundColor: colors.accent},
  buttonActive: {backgroundColor: '#4a3830'},
  buttonPressed: {opacity: 0.7},
  buttonDisabled: {backgroundColor: '#2a2d33'},
  buttonText: {fontSize: 12, fontWeight: '500', color: colors.text},
  buttonPrimaryText: {color: '#302016', fontWeight: '600'},
  disabledText: {color: colors.faint},
  accentText: {color: colors.accent},
  mutedText: {color: colors.muted},
  empty: {flex: 1, justifyContent: 'center', alignItems: 'center', padding: 35, gap: 14},
  emptyIcon: {width: 64, height: 54, borderRadius: 12, borderWidth: 1, borderColor: '#454952', backgroundColor: '#24272d', justifyContent: 'center', alignItems: 'center'},
  emptyIconText: {fontSize: 25, color: '#b7bcc6'},
  emptyTitle: {color: colors.text, fontSize: 20, fontWeight: '600', letterSpacing: -0.4, textAlign: 'center'},
  emptyBody: {color: colors.muted, fontSize: 13, lineHeight: 20, textAlign: 'center', maxWidth: 310, marginBottom: 7},
  modalBackdrop: {...StyleSheet.absoluteFillObject, zIndex: 1000, backgroundColor: '#00000080', justifyContent: 'center', alignItems: 'center', padding: 30},
  modal: {width: 390, maxWidth: '100%', backgroundColor: '#2b2e35', borderWidth: 1, borderColor: '#4b4f58', borderRadius: 13, padding: 24},
  modalTitle: {color: colors.text, fontSize: 20, fontWeight: '600', letterSpacing: -0.4, marginBottom: 10},
  modalBody: {color: colors.muted, fontSize: 13, lineHeight: 20, marginBottom: 19},
  modalActions: {flexDirection: 'row', justifyContent: 'flex-end', gap: 8, marginTop: 20},
  loading: {flex: 1, alignItems: 'center', justifyContent: 'center', gap: 16},
});
